overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  form-data@<2.5.4: '>=2.5.4'
  nth-check@<2.0.1: '>=2.0.1'
  tough-cookie@<4.1.3: '>=4.1.3'
  undici@<5.29.0: '>=5.29.0'
  undici@>=4.5.0 <5.28.5: '>=5.28.5'
